Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,20 +7,24 @@ jobs:
     
       - uses: actions/checkout@v2
       
-      - name: Get Version
+      - name: Version
         run: |
           export VERSION=$(cat VERSION)
+          [[ -z "$VERSION" ]] && { echo "ERROR: File VERSION not found or empty"; exit 1; }
           echo $VERSION
         
-      - name: Get Release Id
+      - name: Release
         run: |
           export RELEASEID=$(echo $(curl -X GET -H "Accept: application/vnd.github.v3+json" \
           ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases/tags/${VERSION}) | jq -r '.id')
+          if [[ -z "$RELEASEID" ]]
+          do
+            curl -X POST -H "Accept: application/vnd.github.v3+json" \
+            ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases \
+            -d '{"tag_name":"${VERSION}","target_commitish":"${GITHUB_SHA}"}'
+          else
+            curl -X PATCH -H "Accept: application/vnd.github.v3+json" \
+            ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases/tags/${RELEASEID} \
+            -d '{"target_commitish":"${GITHUB_SHA}"}'
+          fi
           echo $RELEASEID
-        
-      - name: Update Release
-        run: |
-          curl -X PATCH -H "Accept: application/vnd.github.v3+json" \
-          ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases/tags/${RELEASEID} \
-          -d '{"target_commitish":"${GITHUB_SHA}"}'
-        
